services:
  db:
    image: mysql:latest
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kamdanes
      MYSQL_USER: kamdanes
      MYSQL_PASSWORD: nepovem
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 10

  app:
    build: ./app
    restart: always
    container_name: app
    ports:
      - "3000:80"
    volumes:
      - ./app/src:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 10s
      retries: 5

  scraper:
    build: ./scraper
    container_name: scraper
    environment:
      APP_URL: http://app
    depends_on:
      app:
        condition: service_healthy
    env_file:
      - .env

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
