FROM php:8.3-apache

WORKDIR /var/www/html

COPY ./src /var/www/html

RUN docker-php-ext-install pdo pdo_mysql

RUN a2enmod rewrite

RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf

COPY ./apache2.conf /etc/apache2/sites-available/000-default.conf

RUN apachectl configtest

CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]