FROM php:8.3-apache

WORKDIR /var/www/html

COPY ./src /var/www/html

RUN docker-php-ext-install pdo pdo_mysql

RUN echo "ServerName localhost:80" >> /etc/apache2/apache2.conf

CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]